### ISSUE TITLE
How to determine corresponding sql file during error on migration

### ISSUE THREAD

**Issue by rkosafo** [rspeele/Rezoom.SQL#17]
Is there a way to indicate or determine the sql file responsible for an error during migration?

When there are migration errors (from using the vendor statement a lot), the exception shown is the correct sql error but when multiple sql files were added running the application, it can be a bit difficult to identify which file generated the error.

Example error
![2017-08-22 01_32_59-notificationsform](https://user-images.githubusercontent.com/21700034/29544973-1ea170fc-86db-11e7-90ac-199ea8187b71.png)

**Comment by rspeele** [comment]
Good point, these should probably be wrapped in an outer exception containing the filename.

**Comment by rkosafo** [comment]
@rspeele What is the final decision on this? Is it to write the outer exception as indicated above or have you decided on some other approach?

**Comment by rspeele** [comment]
Definitely outer exception as above and it's honestly a tiny change, I have just been completely unmotivated in the past couple months. Sorry!

(edit: I have written a commit to help with this, hoping to fix a few of the other quick issues before putting up a new NuGet package)
