### ISSUE TITLE
[tsql] Delete column used in FK relationship

### ISSUE THREAD

**Issue by rkosafo** [rspeele/Rezoom.SQL#2]
Hi,
How does one delete a column with a constraint - particularly foreign key?

`memberId int64 null references Members(id)`

`Alter table ... drop column ...` gives an error that the column cannot be dropped because it is referenced by constraints ... .

I'm not sure how to drop the constraint.

## Work around
I used the `vendor` statement to delete the constraint and the column. The issue is what to put in `imagine` so that the column is removed. Using `alter table ... drop column ...` in `imagine` gives the same error as before.

For now, `imagine` is empty. The output from `select *` still has the deleted column.

What is the correct way to delete a column in this case?

**Comment by piaste** [comment]
https://rspeele.gitbooks.io/rezoom-sql/doc/Language/AlterTableStmt.html

Assuming you didn't name the foreign key constraint, the delete statement should be;

    ALTER TABLE TableName DROP CONSTRAINT TableName_a_b_FK_OtherTable_c_d

**Comment by rspeele** [comment]
Piaste is correct. Check out [this example](http://rzsql.net/#0D84338DA7E1CA1CA79E6A4963587889A0D81A95).

**Comment by rkosafo** [comment]
Thanks. It worked. Checked `DropStmt` instead :(
