### ISSUE TITLE
No compile time error when using Inner Join without On

### ISSUE THREAD

**Issue by rkosafo** [rspeele/Rezoom.SQL#22]
When an inner join is written without `on`, it does not fail at compile time but rather give a runtime error like `Incorrect syntax near ';'.`.

Using the default model and tsql,

```fsharp
module Tests =
  let print = printf "Output: %A"

  type InnerJoinWithoutOn = SQL<"""
    Select *
    From Users u
    Inner Join Comments c --ON is missing """>
  let innerJoinWithoutOn () = 
    use ctx = new ConnectionContext ()
    InnerJoinWithoutOn.Command().Execute (ctx) |> print
 ````

It will be nice if this can fail at compile time instead of at runtime.

**Comment by rspeele** [comment]
This is actually legal syntax in SQLite, but it does seem pretty pointless, so it might as well be an error on all backends.

**Comment by rspeele** [comment]
a178ba7c922f55685c40bfbdfde0f96e9921aebc should knock this one out. All joins will require "on <condition>" except comma-joins like `select * from a, b, c where ...`.
