### ISSUE TITLE
Ambiguous columns not recognized with *

### ISSUE THREAD

**Issue by rkosafo** [rspeele/Rezoom.SQL#23]
Given the query

```sql
Select *
From Users u
Inner Join Comments c on u.id = c.authorId
```

The `id` field is duplicated. In the final object, `Comments.Id` is used while `User.id` is ignored. Is it possible to have it fail as it will be easy to get the wrong data?

This however gives the right exception
```sql
Select id, *
From Users u
Inner Join Comments c on u.id = c.authorId
```

It must be noted that the current behaviour is consistent though with SSMS.

**Comment by rspeele** [comment]
I agree with you, this is a mistake on RZSQL's part regardless of the SSMS behavior. Duplicate column names should always be an error.

**Comment by rspeele** [comment]
a3be5f1 should fix this, again I am delaying the NuGet package release till I get around to fixing a couple more things.
