### ISSUE TITLE
Rezoom overwrite V1.model.sql and rzsql.json with paket update

### ISSUE THREAD

**Issue by Risord** [rspeele/Rezoom.SQL#9]
Hi

I converted yesterday db schema to rezoom, run migrations, did paket update and made commit. Today I noticed it's all gone and initial migraiont was replaced by hello world one. Content of database is only evidence that yesterday I had something. I was able to replicate loss and paket update seems to be the thing.

Edit: Nuget packages used:
Rezoom.SQL.Provider
Rezoom.SQL.Provider.TSQL

**Comment by rspeele** [comment]
Hi,

Thank you for reporting this issue. I've never used Paket, and NuGet always asks before overwriting files if the local file has changed from the one in the currently installed package version.

Paket apparently does not ask, but has an option to not overwrite changed content files:

https://github.com/fsprojects/Paket/issues/202

See [this comment](https://github.com/fsprojects/Paket/issues/202#issuecomment-259551334) in particular for the Paket options related to content files.

Had I known about this, I probably would not have taken the approach of building NuGet packages with "helper" files for getting started. Given that the packages already exist, I will add a warning for Paket users in the tutorial and documentation.

**Comment by rspeele** [comment]
I have updated the tutorial to include a warning and advice for how to safely set up the dependencies with Paket.
